server.port=8083
spring.application.name=product-service

# Register with Eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
